// Interface automatically generated by schemas-to-ts

export interface Plan {
  name?: string;
  description?: string;
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
}
export interface Plan_Plain {
  name?: string;
  description?: string;
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
}

export interface Plan_NoRelations {
  name?: string;
  description?: string;
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
}

