// Interface automatically generated by schemas-to-ts

import { Organisation } from '../../../organisation/content-types/organisation/organisation';
import { Organisation_Plain } from '../../../organisation/content-types/organisation/organisation';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Assurance {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    organisationId?: { data: Organisation };
    certificationProgramme?: string;
    stageOfCertificationInProgramme?: string;
    auditObjectives?: string;
    scope?: string;
    reportingBaseYearStartDate?: Date;
    reportingBaseYearEndDate?: Date;
    reportingYearStartDate?: Date;
    reportingYearEndDate?: Date;
    excludedBusinessUnitIds?: any;
    consolidationMethod?: string;
    auditType?: string;
    geographicalBoundaries?: any;
    typeOfGHG?: any;
    assuranceLevels?: any;
    inventoryCompilationProcess?: any;
    quantificationApproach?: any;
    statementOfIntent?: string;
    intendedUse?: any;
    excludeEmissionSources?: any;
    executiveSummary?: string;
    status?: string;
    auditCriteria?: string;
    auditDate?: Date;
    materialityMandatory?: number;
    materialitySupplyOptional?: number;
    isConsolidationMethodChangeApproved?: string;
    isReportingMethodAppropriate?: string;
    systemOrSoftwareComment?: string;
    systemOrSoftwareUsed?: string;
  };
}
export interface Assurance_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  organisationId?: Organisation_Plain;
  certificationProgramme?: string;
  stageOfCertificationInProgramme?: string;
  auditObjectives?: string;
  scope?: string;
  reportingBaseYearStartDate?: Date;
  reportingBaseYearEndDate?: Date;
  reportingYearStartDate?: Date;
  reportingYearEndDate?: Date;
  excludedBusinessUnitIds?: any;
  consolidationMethod?: string;
  auditType?: string;
  geographicalBoundaries?: any;
  typeOfGHG?: any;
  assuranceLevels?: any;
  inventoryCompilationProcess?: any;
  quantificationApproach?: any;
  statementOfIntent?: string;
  intendedUse?: any;
  excludeEmissionSources?: any;
  executiveSummary?: string;
  status?: string;
  auditCriteria?: string;
  auditDate?: Date;
  materialityMandatory?: number;
  materialitySupplyOptional?: number;
  isConsolidationMethodChangeApproved?: string;
  isReportingMethodAppropriate?: string;
  systemOrSoftwareComment?: string;
  systemOrSoftwareUsed?: string;
}

export interface Assurance_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  organisationId?: number;
  certificationProgramme?: string;
  stageOfCertificationInProgramme?: string;
  auditObjectives?: string;
  scope?: string;
  reportingBaseYearStartDate?: Date;
  reportingBaseYearEndDate?: Date;
  reportingYearStartDate?: Date;
  reportingYearEndDate?: Date;
  excludedBusinessUnitIds?: any;
  consolidationMethod?: string;
  auditType?: string;
  geographicalBoundaries?: any;
  typeOfGHG?: any;
  assuranceLevels?: any;
  inventoryCompilationProcess?: any;
  quantificationApproach?: any;
  statementOfIntent?: string;
  intendedUse?: any;
  excludeEmissionSources?: any;
  executiveSummary?: string;
  status?: string;
  auditCriteria?: string;
  auditDate?: Date;
  materialityMandatory?: number;
  materialitySupplyOptional?: number;
  isConsolidationMethodChangeApproved?: string;
  isReportingMethodAppropriate?: string;
  systemOrSoftwareComment?: string;
  systemOrSoftwareUsed?: string;
}

export interface Assurance_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  organisationId?: AdminPanelRelationPropertyModification<Organisation_Plain>;
  certificationProgramme?: string;
  stageOfCertificationInProgramme?: string;
  auditObjectives?: string;
  scope?: string;
  reportingBaseYearStartDate?: Date;
  reportingBaseYearEndDate?: Date;
  reportingYearStartDate?: Date;
  reportingYearEndDate?: Date;
  excludedBusinessUnitIds?: any;
  consolidationMethod?: string;
  auditType?: string;
  geographicalBoundaries?: any;
  typeOfGHG?: any;
  assuranceLevels?: any;
  inventoryCompilationProcess?: any;
  quantificationApproach?: any;
  statementOfIntent?: string;
  intendedUse?: any;
  excludeEmissionSources?: any;
  executiveSummary?: string;
  status?: string;
  auditCriteria?: string;
  auditDate?: Date;
  materialityMandatory?: number;
  materialitySupplyOptional?: number;
  isConsolidationMethodChangeApproved?: string;
  isReportingMethodAppropriate?: string;
  systemOrSoftwareComment?: string;
  systemOrSoftwareUsed?: string;
}
