// Interface automatically generated by schemas-to-ts

export interface AgendaDay {
  AgendaDayDate?: Date;
  AgendaDayText?: string;
}
export interface AgendaDay_Plain {
  AgendaDayDate?: Date;
  AgendaDayText?: string;
}

export interface AgendaDay_NoRelations {
  AgendaDayDate?: Date;
  AgendaDayText?: string;
}

