// Interface automatically generated by schemas-to-ts

export enum CommunicationsMethod {
  MsTeams = 'MS Teams',
  Skype = 'Skype',
  GoogleMeet = 'Google Meet',
  Slack = 'Slack',
  Other = 'Other',}

export interface AgendaItem {
  Location?: string;
  Time?: Date;
  Activity?: string;
  ResourcesRequired?: string;
  communicationsMethod?: CommunicationsMethod;
  activityDescription?: string;
}
export interface AgendaItem_Plain {
  Location?: string;
  Time?: Date;
  Activity?: string;
  ResourcesRequired?: string;
  communicationsMethod?: CommunicationsMethod;
  activityDescription?: string;
}

export interface AgendaItem_NoRelations {
  Location?: string;
  Time?: Date;
  Activity?: string;
  ResourcesRequired?: string;
  communicationsMethod?: CommunicationsMethod;
  activityDescription?: string;
}

