// Interface automatically generated by schemas-to-ts

export interface Option {
  value?: string;
  label?: string;
}
export interface Option_Plain {
  value?: string;
  label?: string;
}

export interface Option_NoRelations {
  value?: string;
  label?: string;
}

