// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Slider {
  files?: { data: Media[] };
}
export interface Slider_Plain {
  files?: Media[];
}

export interface Slider_NoRelations {
  files?: number[];
}

