// Interface automatically generated by schemas-to-ts

export interface Anzsic {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    division?: string;
    code?: string;
    divisionCode?: string;
    subdivision?: string;
    group?: string;
    class?: string;
    label?: string;
    risk?: string;
    emissionData?: any;
  };
}
export interface Anzsic_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  division?: string;
  code?: string;
  divisionCode?: string;
  subdivision?: string;
  group?: string;
  class?: string;
  label?: string;
  risk?: string;
  emissionData?: any;
}

export interface Anzsic_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  division?: string;
  code?: string;
  divisionCode?: string;
  subdivision?: string;
  group?: string;
  class?: string;
  label?: string;
  risk?: string;
  emissionData?: any;
}

export interface Anzsic_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  division?: string;
  code?: string;
  divisionCode?: string;
  subdivision?: string;
  group?: string;
  class?: string;
  label?: string;
  risk?: string;
  emissionData?: any;
}
