// Interface automatically generated by schemas-to-ts

import { Logo } from './Logo';
import { Link } from '../../links/interfaces/Link';
import { Logo_Plain } from './Logo';
import { Link_Plain } from '../../links/interfaces/Link';
import { Logo_NoRelations } from './Logo';
import { Link_NoRelations } from '../../links/interfaces/Link';

export interface Footer {
  footerLogo?: Logo;
  menuLinks: Link[];
  legalLinks: Link[];
}
export interface Footer_Plain {
  footerLogo?: Logo_Plain;
  menuLinks: Link_Plain[];
  legalLinks: Link_Plain[];
}

export interface Footer_NoRelations {
  footerLogo?: Logo_NoRelations;
  menuLinks: Link_NoRelations[];
  legalLinks: Link_NoRelations[];
}

