// Interface automatically generated by schemas-to-ts

import { AssuranceField } from '../../repeating/interfaces/AssuranceField';
import { AssuranceField_Plain } from '../../repeating/interfaces/AssuranceField';
import { AssuranceField_NoRelations } from '../../repeating/interfaces/AssuranceField';

export interface Test2 {
  stuff?: AssuranceField;
  more?: AssuranceField;
}
export interface Test2_Plain {
  stuff?: AssuranceField_Plain;
  more?: AssuranceField_Plain;
}

export interface Test2_NoRelations {
  stuff?: AssuranceField_NoRelations;
  more?: AssuranceField_NoRelations;
}

