// Interface automatically generated by schemas-to-ts

import { AssuranceField } from '../../repeating/interfaces/AssuranceField';
import { AssuranceField_Plain } from '../../repeating/interfaces/AssuranceField';
import { AssuranceField_NoRelations } from '../../repeating/interfaces/AssuranceField';

export interface Test1 {
  intendedUse?: AssuranceField;
  assuranceLevel?: AssuranceField;
  auditDate?: AssuranceField;
}
export interface Test1_Plain {
  intendedUse?: AssuranceField_Plain;
  assuranceLevel?: AssuranceField_Plain;
  auditDate?: AssuranceField_Plain;
}

export interface Test1_NoRelations {
  intendedUse?: AssuranceField_NoRelations;
  assuranceLevel?: AssuranceField_NoRelations;
  auditDate?: AssuranceField_NoRelations;
}

