// Interface automatically generated by schemas-to-ts

import { BusinessUnit } from '../../../business-unit/content-types/business-unit/business-unit';
import { BusinessUnit_Plain } from '../../../business-unit/content-types/business-unit/business-unit';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Address {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    streetAddress?: string;
    suburb?: string;
    city?: string;
    stateOrProvince?: string;
    postCode?: string;
    country?: string;
    isPrimaryAddress?: boolean;
    businessUnitId?: { data: BusinessUnit };
  };
}
export interface Address_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  streetAddress?: string;
  suburb?: string;
  city?: string;
  stateOrProvince?: string;
  postCode?: string;
  country?: string;
  isPrimaryAddress?: boolean;
  businessUnitId?: BusinessUnit_Plain;
}

export interface Address_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  streetAddress?: string;
  suburb?: string;
  city?: string;
  stateOrProvince?: string;
  postCode?: string;
  country?: string;
  isPrimaryAddress?: boolean;
  businessUnitId?: number;
}

export interface Address_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  streetAddress?: string;
  suburb?: string;
  city?: string;
  stateOrProvince?: string;
  postCode?: string;
  country?: string;
  isPrimaryAddress?: boolean;
  businessUnitId?: AdminPanelRelationPropertyModification<BusinessUnit_Plain>;
}
