// Interface automatically generated by schemas-to-ts

import { Assurance } from '../../../assurance/content-types/assurance/assurance';
import { Note } from '../../../note/content-types/note/note';
import { OptionSet } from '../../../option-set/content-types/option-set/option-set';
import { Reference } from '../../../reference/content-types/reference/reference';
import { Assurance_Plain } from '../../../assurance/content-types/assurance/assurance';
import { Note_Plain } from '../../../note/content-types/note/note';
import { OptionSet_Plain } from '../../../option-set/content-types/option-set/option-set';
import { Reference_Plain } from '../../../reference/content-types/reference/reference';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Status {
  Pending = 'pending',
  Complete = 'complete',
  Approved = 'approved',
  Rejected = 'rejected',}
export enum Type {
  Text = 'text',
  Number = 'number',
  Boolean = 'boolean',
  Email = 'email',
  Phone = 'phone',
  DatePicker = 'datePicker',
  DateTimePicker = 'dateTimePicker',
  Select = 'select',
  MultiSelect = 'multiSelect',
  RadioButton = 'radioButton',}

export interface AaAssuranceLevel {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    label?: string;
    value?: string;
    helpText?: string;
    status?: Status;
    type?: Type;
    validation?: string;
    assurance?: { data: Assurance };
    notes: { data: Note[] };
    optionSet?: { data: OptionSet };
    references: { data: Reference[] };
  };
}
export interface AaAssuranceLevel_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  label?: string;
  value?: string;
  helpText?: string;
  status?: Status;
  type?: Type;
  validation?: string;
  assurance?: Assurance_Plain;
  notes: Note_Plain[];
  optionSet?: OptionSet_Plain;
  references: Reference_Plain[];
}

export interface AaAssuranceLevel_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  label?: string;
  value?: string;
  helpText?: string;
  status?: Status;
  type?: Type;
  validation?: string;
  assurance?: number;
  notes: number[];
  optionSet?: number;
  references: number[];
}

export interface AaAssuranceLevel_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  label?: string;
  value?: string;
  helpText?: string;
  status?: Status;
  type?: Type;
  validation?: string;
  assurance?: AdminPanelRelationPropertyModification<Assurance_Plain>;
  notes: AdminPanelRelationPropertyModification<Note_Plain>;
  optionSet?: AdminPanelRelationPropertyModification<OptionSet_Plain>;
  references: AdminPanelRelationPropertyModification<Reference_Plain>;
}
