// Interface automatically generated by schemas-to-ts

export interface Reference {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    referenceText?: string;
    referenceUrl?: string;
  };
}
export interface Reference_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  referenceText?: string;
  referenceUrl?: string;
}

export interface Reference_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  referenceText?: string;
  referenceUrl?: string;
}

export interface Reference_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  referenceText?: string;
  referenceUrl?: string;
}
