// Interface automatically generated by schemas-to-ts

import { Contact } from '../../../contact/content-types/contact/contact';
import { Assurance } from '../../../assurance/content-types/assurance/assurance';
import { Anzsic } from '../../../anzsic/content-types/anzsic/anzsic';
import { Contact_Plain } from '../../../contact/content-types/contact/contact';
import { Assurance_Plain } from '../../../assurance/content-types/assurance/assurance';
import { Anzsic_Plain } from '../../../anzsic/content-types/anzsic/anzsic';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Organisation {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    legalName?: string;
    type?: string;
    highestParentCompany?: string;
    description?: string;
    statementOfIntent?: string;
    anzsicCode?: string;
    highestParentCompanyID?: number;
    contacts: { data: Contact[] };
    assurances: { data: Assurance[] };
    anzsic?: { data: Anzsic };
  };
}
export interface Organisation_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  legalName?: string;
  type?: string;
  highestParentCompany?: string;
  description?: string;
  statementOfIntent?: string;
  anzsicCode?: string;
  highestParentCompanyID?: number;
  contacts: Contact_Plain[];
  assurances: Assurance_Plain[];
  anzsic?: Anzsic_Plain;
}

export interface Organisation_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  legalName?: string;
  type?: string;
  highestParentCompany?: string;
  description?: string;
  statementOfIntent?: string;
  anzsicCode?: string;
  highestParentCompanyID?: number;
  contacts: number[];
  assurances: number[];
  anzsic?: number;
}

export interface Organisation_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  legalName?: string;
  type?: string;
  highestParentCompany?: string;
  description?: string;
  statementOfIntent?: string;
  anzsicCode?: string;
  highestParentCompanyID?: number;
  contacts: AdminPanelRelationPropertyModification<Contact_Plain>;
  assurances: AdminPanelRelationPropertyModification<Assurance_Plain>;
  anzsic?: AdminPanelRelationPropertyModification<Anzsic_Plain>;
}
