// Interface automatically generated by schemas-to-ts

import { Organisation } from '../../../organisation/content-types/organisation/organisation';
import { Organisation_Plain } from '../../../organisation/content-types/organisation/organisation';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Contact {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    role?: string;
    organisationId?: { data: Organisation };
  };
}
export interface Contact_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  role?: string;
  organisationId?: Organisation_Plain;
}

export interface Contact_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  role?: string;
  organisationId?: number;
}

export interface Contact_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  role?: string;
  organisationId?: AdminPanelRelationPropertyModification<Organisation_Plain>;
}
