// Interface automatically generated by schemas-to-ts

export interface DataEntry {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    value?: string;
    source?: string;
  };
}
export interface DataEntry_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  value?: string;
  source?: string;
}

export interface DataEntry_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  value?: string;
  source?: string;
}

export interface DataEntry_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  value?: string;
  source?: string;
}
