// Interface automatically generated by schemas-to-ts

export interface Features {
  heading?: string;
  description?: string;
}
export interface Features_Plain {
  heading?: string;
  description?: string;
}

export interface Features_NoRelations {
  heading?: string;
  description?: string;
}

