// Interface automatically generated by schemas-to-ts

export interface Pricing {
  title?: string;
}
export interface Pricing_Plain {
  title?: string;
}

export interface Pricing_NoRelations {
  title?: string;
}

