// Interface automatically generated by schemas-to-ts

export interface TestimonialsGroup {
  title?: string;
  description?: string;
}
export interface TestimonialsGroup_Plain {
  title?: string;
  description?: string;
}

export interface TestimonialsGroup_NoRelations {
  title?: string;
  description?: string;
}

