// Interface automatically generated by schemas-to-ts

import { Organisation } from '../../../organisation/content-types/organisation/organisation';
import { Assurance } from '../../../assurance/content-types/assurance/assurance';
import { AssuranceField } from '../../../../components/repeating/interfaces/AssuranceField';
import { AaAssuranceLevel } from '../../../aa-assurance-level/content-types/aa-assurance-level/aa-assurance-level';
import { Organisation_Plain } from '../../../organisation/content-types/organisation/organisation';
import { Assurance_Plain } from '../../../assurance/content-types/assurance/assurance';
import { AssuranceField_Plain } from '../../../../components/repeating/interfaces/AssuranceField';
import { AaAssuranceLevel_Plain } from '../../../aa-assurance-level/content-types/aa-assurance-level/aa-assurance-level';
import { AssuranceField_NoRelations } from '../../../../components/repeating/interfaces/AssuranceField';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface StrategicAnalysis {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    organisation?: { data: Organisation };
    assurance?: { data: Assurance };
    fields: AssuranceField[];
    aa_assurance_level?: { data: AaAssuranceLevel };
    aaassurance2?: { data: AaAssuranceLevel };
  };
}
export interface StrategicAnalysis_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organisation?: Organisation_Plain;
  assurance?: Assurance_Plain;
  fields: AssuranceField_Plain[];
  aa_assurance_level?: AaAssuranceLevel_Plain;
  aaassurance2?: AaAssuranceLevel_Plain;
}

export interface StrategicAnalysis_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organisation?: number;
  assurance?: number;
  fields: AssuranceField_NoRelations[];
  aa_assurance_level?: number;
  aaassurance2?: number;
}

export interface StrategicAnalysis_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organisation?: AdminPanelRelationPropertyModification<Organisation_Plain>;
  assurance?: AdminPanelRelationPropertyModification<Assurance_Plain>;
  fields: AssuranceField_Plain[];
  aa_assurance_level?: AdminPanelRelationPropertyModification<AaAssuranceLevel_Plain>;
  aaassurance2?: AdminPanelRelationPropertyModification<AaAssuranceLevel_Plain>;
}
