// Interface automatically generated by schemas-to-ts

import { Option } from '../../../../components/repeating/interfaces/Option';
import { Option_Plain } from '../../../../components/repeating/interfaces/Option';
import { Option_NoRelations } from '../../../../components/repeating/interfaces/Option';

export interface OptionSet {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    setName?: string;
    options: Option[];
  };
}
export interface OptionSet_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  setName?: string;
  options: Option_Plain[];
}

export interface OptionSet_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  setName?: string;
  options: Option_NoRelations[];
}

export interface OptionSet_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  setName?: string;
  options: Option_Plain[];
}
